#!/bin/bash
XPI=fxos-tv@mozilla.org.xpi
INST_PAGE=install.html

# Remove the add-on file from your device
adb shell rm /sdcard/$INST_PAGE && \
adb shell rm /sdcard/$XPI \

# Remove the add-on file in this computer
rm $XPI

echo Remove $XPI and $INST_PAGE from device\'s /sdcard
